apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kbxi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kbxi
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kbxi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kbxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kbxi
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wbiu-tenant/rhtap-demo-app/hacbs-test-project-kbxi@sha256:212e7b03c584802dab09b78d23b04e222e82d05c7be652d4675c20fe93e9cdf5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
