apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kbxi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wbiu-tenant/rhtap-demo-app/hacbs-test-project-kbxi@sha256:0c16542125af398636d9fe523beb5d5a201123a137ac6ef09e4e625856ccc6e8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
