apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kbxi
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wbiu-tenant/rhtap-demo-app/hacbs-test-project-kbxi@sha256:6552a5b24e4399b37170f3bdf4de8034052cec937bb7792edec98ac2a36c94aa
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
